services:
  server:
    image: tasktracker-server:latest  # Create the local image: docker build --platform linux/amd64 -t tasktracker-server .
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://host.docker.internal:5432/koala
      - DB_USERNAME=
      - DB_PASSWORD=