pluginName: "Do bugs makes programmers cry?"
pluginDescription: "We want to track your progress through the study in order to collect data on file changes during the study completion. Please, when you are ready, press the next button."
researchId: "Example"
