scenario:
  steps:
    - units:
        - !<Task>
          id: "question1"
        - !<Task>
          id: "question2"
        - !<Task>
          id: "question3"
        - !<Task>
          id: "question4"
        - !<Task>
          id: "question5"
        - !<Task>
          id: "question6"
