tasks:

  - description: "Complete the task using the instructions on LimeSurvey. The task file will be under tasktracker/python/CalculateGPAStatementCoverage/src. /n/n After completing the task, and submitting the files on LimeSurvey, click next. Statement Coverage: Causes every statement in the program to be executed at least once, giving us confidence that every statement is at least capable of executing correctly.\n\nSystem: Make a test case for each statement in the program, independent of the others.\n\nCompletion criterion: A test case for every statement.\n\nNote: You only need to do statement coverage for the provided code for this study.\n\nWhen you are done the task, please back up the file in a separate location before submitting it.\n\nThe files can be found in the tasktracker directory.\n\nYou will need to import print_error.py and pytest."
    id: statement_coverage
    name: "Calculate GPA Statement Coverage"
    focusFileId: "test_calculate_gpa"
    files:
      - filename: "test_calculate_gpa"
        sourceSet: "SRC"
        extension: PYTHON
        id: "test_calculate_gpa"
      - filename: "calculate_gpa"
        sourceSet: "SRC"
        templateFile: "calculate_gpa"
        extension: PYTHON
        id: "calculate_gpa"
    openAllFiles: true

  - description: "Complete the task using the instructions on LimeSurvey. The task file will be under tasktracker/python/CheckParcelBranchCoverage/src. /n/n After completing the task, and submitting the files on LimeSurvey, click next. Branch Coverage: Causes every decision (if, switch, while, etc.) in the program to be made both ways (or every possible way for switch).\n\nSystem: Design a test case to exercise each decision in the program each way (true/false).\n\nCompletion criterion: A test case for each side of each decision.\n\nNote: You only need to do branch coverage for the provided code for this study.\n\nWhen you are done the task, please back up the file in a separate location before submitting it.\n\nThe files can be found in the tasktracker directory.\n\nYou will need to import write.py and pytest."
    id: branch_coverage
    name: "Check Parcel Branch Coverage"
    focusFileId: "test_check_parcel"
    files:
      - filename: "test_check_parcel"
        sourceSet: "SRC"
        extension: PYTHON
        id: "test_check_parcel"
      - filename: "check_parcel"
        sourceSet: "SRC"
        templateFile: "check_parcel"
        extension: PYTHON
        id: "check_parcel"
    openAllFiles: true

#  - description: "Sample Task - Statement Coverage: This task is a sample for reference only to show what a basic Python unit test using pytest looks like.\n\nStatement Coverage: Causes every statement in the program to be executed at least once, giving us confidence that every statement is at least capable of executing correctly.\n\nSystem: Make a test case for each statement in the program, independent of the others.\n\nCompletion criterion: A test case for every statement.\n\nNote: You only need to do statement coverage for the provided code for this study.\n\nWhen you are done the task, please back up the file in a separate location before submitting it.\n\nThe files can be found in the tasktracker directory.\n\nYou will need to import print_error.py and pytest."
#    id: sample_statement_coverage
#    name: "Statement Coverage Sample"
#    focusFileId: "statement_coverage_sample"
#    files:
#      - filename: "test_sample"
#        sourceSet: "SRC"
#        templateFile: "test_sample"
#        extension: PYTHON
#        id: "test_sample_file"
#      - filename: "sample"
#        sourceSet: "SRC"
#        templateFile: "sample"
#        extension: PYTHON
#        id: "sample"
#    openAllFiles: true